# Generated by Django 3.2.9 on 2022-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(default='johndoe@test.com', max_length=160),
            preserve_default=False,
        ),
    ]
