# Generated by Django 3.2.9 on 2022-01-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageCategory',
            new_name='Category',
        ),
    ]
