# Generated by Django 3.2.9 on 2022-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='selection',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
