# Generated by Django 3.2.9 on 2022-01-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0009_auto_20220107_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.actor')),
            ],
        ),
    ]
