# Generated by Django 3.2.9 on 2022-01-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='star',
            new_name='star_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='star_autograph_category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='star_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='star_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='star_photoshoot_category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
