# Generated by Django 3.2.9 on 2022-01-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20220107_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(blank=True, max_length=60, null=True)),
                ('star_autograph_category', models.CharField(blank=True, max_length=1, null=True)),
                ('star_photoshoot_category', models.CharField(blank=True, max_length=1, null=True)),
                ('star_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('star_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='star_autograph_category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='star_image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='star_image_url',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='star_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='star_photoshoot_category',
        ),
    ]
