# Generated by Django 3.2.9 on 2022-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price_category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
