# Generated by Django 3.2.9 on 2022-01-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_price_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='star_name',
            new_name='name',
        ),
    ]
