# Generated by Django 3.2.9 on 2022-01-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_rename_star_name_actor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_num',
            field=models.DecimalField(decimal_places=0, default=99, max_digits=2),
        ),
    ]
