# Generated by Django 3.2.9 on 2022-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(default='first_name last_name', max_length=60),
        ),
        migrations.AlterField(
            model_name='actor',
            name='star_autograph_category',
            field=models.CharField(default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='actor',
            name='star_image',
            field=models.ImageField(default='noimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='actor',
            name='star_photoshoot_category',
            field=models.CharField(default='B', max_length=1),
        ),
    ]
