# Generated by Django 3.2.9 on 2022-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20220214_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='actor',
            name='star_autograph_category',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='actor',
            name='star_photoshoot_category',
            field=models.CharField(max_length=1),
        ),
    ]
