# Generated by Django 3.2.9 on 2022-02-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20220214_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='star_imdb',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='star_info_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='star_info_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='star_official',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='star_wiki',
            field=models.URLField(default='https://en.wikipedia.org/wiki/<django.db.models.fields.CharField>', max_length=1024),
        ),
    ]
