# Generated by Django 3.2.9 on 2022-02-17 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_auto_20220216_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='star_autograph_category',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-C]$')]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='star_photoshoot_category',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-C]$')]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='star_wiki',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
