# Generated by Django 3.2.9 on 2022-02-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_auto_20220217_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='goodies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
